std_msgs/Header                 header
Oem7Header                      nov_header
SolutionStatus                  sol_status
PositionOrVelocityType          pos_type
float64                         east
float64                         north
float64                         up
float32                         east_stdev
float32                         north_stdev
float32                         up_stdev
int8[4]                         rover_stn_id
int8[4]                         master_stn_id
uint8                           num_sv_tracked
uint8                           num_sv_in_sol
uint8                           num_sv_obs
uint8                           num_sv_multi
uint8                           reserved
BestExtendedSolutionStatus      ext_sol_status
uint8                           galileo_beidou_sig_mask
uint8                           gps_glonass_sig_mask





