# Oem7 messages; message names and IDs are as they appear in Oem7 manual.
# Correctness of message ID is critical for correct operation.
oem7_raw_msgs:
# Standard messages - Do not remove.
- 42    # BESTPOS
- 99    # BESTVEL
- 1429  # BESTGNSSPOS
- 1538  # PPPPOS
- 1465  # INSPVAX
- 1825  # INSUPDATESTATUS
- 1462  # RAWIMUSX
- 41    # RAWEPHEM
- 723   # GLOEPHEMERIS
- 1696  # BDSEPHEMERIS
- 1310  # GALFNAVEPHEMERIS
- 1309  # GALINAVEPHEMERIS
- 43    # RANGE
- 1335  # HEADING2
- 101   # TIME
- 93    # RXSTATUS
- 1945  # INSCONFIG
- 1719  # TERRASTARINFO
- 1720  # TERRASTARSTATUS
# More messages may be added in order to process Oem7 'raw' messages.
- 83    # TRACKSTAT
