oem7_msg_handlers:
    - ALIGNHandler      # does not depend on anything
    - INSHandler        # depends on ALIGN
    - BESTPOSHandler    # depends on INS
    - RXSTATUSHandler
    - TimeHandler
    - NMEAHandler
    - OdometryHandler   # depends on BESTPOS and INS
